version: "3"

services:
  vote:
    image: "martin22ca/entrega_vote:${VERSION_TAG}"
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: "martin22ca/entrega_result:${VERSION_TAG}"
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: "martin22ca/entrega_worker:${VERSION_TAG}"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
